language: python
notifications:
  email:
    on_failure: change
sudo: false
cache: pip
python:
- '2.7'
- '3.5'
- '3.6'
install:
- make setup
script:
- make test
deploy:
  provider: pypi
  edge:
    branch: v1.8.45
  user: evhub-develop
  password:
    secure: IU7eaXynfISKevmKviLr3pjVkxvjB6TIyrTXMYHVs2f+XhBUF4zF6cwyglFAJIA0ZzezAkHX/UBP3djL98YDZG14VKRzVIIlsUtjp4QIQrRU5/fgSw8qO0tLP7KmPvq2VmWJseZXgZtekjIN0LjmHWHIXJ0fvcOwF0YFaaVfGMOJXixpIBkMPLAcAX6CeIH6PmRSCsg//q3SCJki+nn1m86u9sEdPkR9GmJctjdhsOwOsuOGX2ewBwc0Mi6jWHMfOC5I8z0AEXT5qQuur4C4i4VXCnS9bfvc0yJJshsH8x20nTVA9c79fGS6NzOdZXsJYdp5BuN79sSdOIW2fgCOu5mD/yTXdERF2M2VG7qGiIJsBZPqqDNLsbabhK4nVkpkEhcG3l7TAd9AUfsYTKn/A8t8vevYk3cWoN3+O9znG8HUHyuHCIlct6Y7xcdgsaTMLzasYoorszu68DmkSx9wtXL03l4M/oaggAALxcNLbc5tiKpsYuo6bhtz6dKMnKWnkSP9lIQV4vGgl3iauwNfjZCsW9SbtLVqa6/FOyRJ5JIwTTIutzwmHgP4q8ZAkN04+7gudwehTDPfLusOCmzjkDtwbwCacXIS3GhmS5xjBjOKNyAtgfSNoB7WN+csWrGIDA5wBBl+X5MbZYstmDCPTEygWL8h2LB+9hOlnPrVUPY=
  on:
    distributions: sdist bdist_wheel
    repo: evhub/iternash
