language: python
notifications:
  email:
    on_failure: change
sudo: false
cache: pip
python:
- '2.7'
- '3.5'
- '3.6'
install:
- make setup
script:
- make test
deploy:
  provider: pypi
  edge:
    branch: v1.8.45
  user: evhub-develop
  password:
    secure: 07LkJc/mX6J9eC7uxn0NqCXMbUsFuYg+6OVIst9p9AOXtlEDg8XpxMyAv1pxBhedrDHNOG7doPHdfgCGR9CtfXvw0FkimmK5Wvm9yqArR0cDaT8vEMx2QPm3Ob32h/Yy6ycgi/uJR6+xAQfQW6UU/fyPlb/PwwcgoQ7gC+mjqQIBzNWxvTNL7v1Y46EgICyuY/BBvi74gWvoTucBEY+i9DMsj6xi4EkeyTeywJzPWOwPhVE77GEH8lyR3U4ZPo2a28ztYA48mTWxQl1HHTZ8U3bNg36AKMwYavQQnB+EOODhvbYZYcDy513bWtbMF0bFjduGXUehr3ooYmfVWxoQH56Z6vJosBSadv6Qde4U0OGRSvtQ8wRrxL6zHLPEo/ap7Tm2plW4hdITjwnNp+QNn1wLsKZMcxsRi550BuISnt97Tvhc/cwx6k4Q4bJg9nPakwJHdRzk8PwjLPfkvSTUUckWJSui9ME3gyzFZCwzSXkg27W3LqII/LgCJR2eK4jano2Cc3BQ0c3fKIHzrwcATRWiWbrRbrbEQxPPca/fY5AT1RTLiXiL9sAlejiI0otD0W9qnef9iyDweDFPH6QKNr9y3Iuyd55HrR3Hkw/64PXysWkXt4st+BCAx16Rs2uHf0itT9z7tleXJwfmyyNUuWhNDjHTHekwqbf6FLxVI+E=
  on:
    distributions: sdist bdist_wheel
    repo: evhub/iternash
